describe('login page', () => {
  beforeEach(() => {
    cy.visit('/')
  })

  it('should succeed with keyboard', () => {
    cy.get('article')
      .should('be.visible')
      .find('[name="user"]')
      .click()
      .type('tei')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('[name="password"]')
      .type('simple')
    cy.get('footer > button')
      .contains('Login')
      .click()
    cy.get('#login')
      .should('be.visible') 
  })

  it('should fail without credentials', () => {
    cy.get('article')
      .should('be.visible')
      .find('[name="user"]')
      .type('tei')
    cy.get('footer > button')
      .contains('Login')
      .click()
    cy.get('h2')
      .contains('Login')
      .should('be.visible') 
    cy.get('[key="login.invalid"]')
      .should('be.visible')
  })
})