// StandardJS, should-style assertions
// GUI tests for Pagination functionality
// Generated by jinks - DO NOT EDIT manually

describe('TEI-Publisher Pagination', () => {
  beforeEach(() => {
    // Set desktop viewport to ensure all elements are visible
    cy.viewport(1280, 720)
    
    // Universal intercepts (loginStub, timelineStub) are automatically set up in support/e2e.js
    cy.visit('/browse.html?collection=demo')
    
    // Wait for page to stabilize and pagination to be fully initialized
    cy.get('body').should('be.visible')
    cy.waitForPaginate()
  })

  describe('Pagination Component', () => {
    it('displays pagination component with total count', () => {
      cy.get('pb-paginate')
        .should('be.visible')
        .should('have.attr', 'total')
      
      cy.get('pb-paginate')
        .invoke('attr', 'total')
        .should('not.be.empty')
        .and('not.eq', '0')
      
      // Verify found count is displayed (in Shadow DOM)
      cy.get('pb-paginate')
        .shadow()
        .find('span.found[part="count"]')
        .should('exist')
        .invoke('text')
        .should('not.be.empty')
    })

    it('displays per-page configuration', () => {
      cy.get('pb-paginate')
        .should('have.attr', 'per-page')
      
      cy.get('pb-paginate')
        .invoke('attr', 'per-page')
        .then((perPage) => {
          expect(parseInt(perPage, 10)).to.be.greaterThan(0)
        })
    })

    it('verifies total documents equals pagination count', () => {
      // Get total from pagination component
      cy.getPaginationAttrs()
      
      // Get count from found span in Shadow DOM
      cy.get('pb-paginate')
        .shadow()
        .find('span.found[part="count"]')
        .invoke('text')
        .then((foundText) => {
          // Extract number from text like "Found 7 items"
          const match = foundText.match(/\d+/)
          const foundNumber = match ? parseInt(match[0], 10) : 0
          
          cy.get('@total').then((total) => {
            const totalNumber = parseInt(total, 10)
            expect(foundNumber).to.equal(totalNumber)
          })
        })
    })
  })

  describe('Pagination Navigation', () => {
    it('displays first page correctly', () => {
      cy.get('pb-paginate')
        .invoke('attr', 'total')
        .then((totalStr) => {
          const total = parseInt(totalStr, 10)
          if (total > 0) {
            // On first page, should have documents displayed
            cy.get('main')
              .find('.tei-fileDesc3, .collection-item, [class*="document"]')
              .should('have.length.at.least', 1)
          }
        })
    })

    it('navigates to next page when available', () => {
      cy.get('pb-paginate')
        .invoke('attr', 'total')
        .then((totalStr) => {
          const total = parseInt(totalStr, 10)
          cy.get('pb-paginate')
            .invoke('attr', 'per-page')
            .then((perPageStr) => {
              const perPage = parseInt(perPageStr, 10)
              
              if (total > perPage) {
                // There is a next page - pagination controls are in Shadow DOM
                cy.get('pb-paginate')
                  .shadow()
                  .find('iron-icon[icon="next"]')
                  .should('exist')
                  .closest('span, button, a')
                  .should('not.have.class', 'disabled')
                  .click({ force: true })
                
                // Wait for pagination active page to update
                cy.get('pb-paginate', { timeout: 10000 })
                  .shadow()
                  .find('span.active')
                  .should('exist')
                
                // Verify we're on page 2 or later
                cy.get('pb-paginate')
                  .shadow()
                  .find('span.active')
                  .invoke('text')
                  .then((pageText) => {
                    const pageNum = parseInt(pageText.trim(), 10)
                    expect(pageNum).to.be.greaterThan(1)
                  })
              } else {
                cy.log('Not enough documents for next page test')
              }
            })
        })
    })

    it('navigates to last page and verifies document count', () => {
      cy.get('pb-paginate')
        .invoke('attr', 'total')
        .then((totalStr) => {
          const total = parseInt(totalStr, 10)
          cy.get('pb-paginate')
            .invoke('attr', 'per-page')
            .then((perPageStr) => {
              const perPage = parseInt(perPageStr, 10)
              const modulo = total % perPage
              const expectedPages = modulo === 0 ? total / perPage : Math.floor(total / perPage) + 1
              
              if (total > perPage) {
                // Navigate to last page - pagination controls are in Shadow DOM
                cy.get('pb-paginate')
                  .shadow()
                  .find('iron-icon[icon="last-page"]')
                  .closest('span, button, a')
                  .click({ force: true })
                
                // Wait for pagination active page to update to last page and verify
                cy.get('pb-paginate', { timeout: 10000 })
                  .shadow()
                  .find('span.active')
                  .should('exist')
                  .invoke('text')
                  .then((pageText) => {
                    const pageNum = parseInt(pageText.trim(), 10)
                    expect(pageNum).to.equal(expectedPages)
                  })
                
                // Verify document count on last page
                if (modulo > 0) {
                  cy.get('main')
                    .find('.tei-fileDesc3, .collection-item, [class*="document"]')
                    .should('have.length', modulo)
                } else {
                  cy.get('main')
                    .find('.tei-fileDesc3, .collection-item, [class*="document"]')
                    .should('have.length', perPage)
                }
              } else {
                cy.log('Not enough documents for last page test')
              }
            })
        })
    })
  })

  describe('Pagination Consistency', () => {
    it('verifies documents per page matches configuration', () => {
      cy.get('pb-paginate')
        .invoke('attr', 'per-page')
        .then((perPageStr) => {
          const perPage = parseInt(perPageStr, 10)
          
          if (perPage > 0) {
            // Count documents on current page - count visible li elements in ul.documents
            // Only visible documents count toward the per-page limit
            cy.get('main')
              .find('ul.documents li:visible', { timeout: 10000 })
              .should('have.length.at.least', 1)
              .its('length')
              .then((count) => {
                expect(count).to.be.at.most(perPage)
              })
          }
        })
    })

    it('verifies pagination calculates page count correctly', () => {
      // Get pagination attributes using shared helper
      cy.getPaginationAttrs()
      
      cy.get('@total').then((totalStr) => {
        const total = parseInt(totalStr, 10)
        
        cy.get('@perPage').then((perPageStr) => {
          const perPage = parseInt(perPageStr, 10)
          
          // Ensure perPage is valid
          expect(perPage).to.be.greaterThan(0)
          expect(total).to.be.at.least(0)
          
          // Calculate expected page count (even with 0 results, we have 1 page conceptually)
          const modulo = total % perPage
          const expectedPages = total === 0 ? 1 : (modulo === 0 ? total / perPage : Math.floor(total / perPage) + 1)
          
          // Verify expected page count is at least 1
          expect(expectedPages).to.be.greaterThan(0)
          
          // Verify document count matches expectations
          if (total > 0) {
            // If there are documents, verify that the first page shows documents
            cy.get('main')
              .find('ul.documents li:visible', { timeout: 10000 })
              .should('have.length.at.least', 1)
              .and('have.length.at.most', perPage)
          } else {
            // If no documents, verify "No documents" message or empty state
            cy.get('main')
              .should('exist')
          }
          
          // Verify pagination controls reflect the page count
          if (expectedPages > 1) {
            // Pagination should show page numbers or next/last buttons (in Shadow DOM)
            cy.get('pb-paginate')
              .shadow()
              .find('span.active, button, a')
              .should('exist')
          } else {
            // With only 1 page, verify pagination still shows the active page indicator
            cy.get('pb-paginate')
              .shadow()
              .find('span.active')
              .should('exist')
              .invoke('text')
              .should('eq', '1')
          }
        })
      })
    })
  })
})

