name: Run tests for demo app
description: Run Cypress tests for a demo app checked out in demo/XXX/
inputs:
  app-name:
    required: true
    description: The app name to run test for

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v7
      with:
        name: docker-artifact
        path: path/to/artifacts
    - name: Docker load
      shell: bash
      run: |
        cd path/to/artifacts
        docker load < docker-image.tar

    - name: Start jinks container
      shell: bash
      run: |
        docker run -d \
        --name jinks-server \
        -p 8080:8080 \
        temp/jinks-server:$GITHUB_SHA

    - name: Wait for server to be ready
      shell: bash
      run: |
        echo "Waiting for eXist-db to start..."
        timeout=120
        elapsed=0
        while [ $elapsed -lt $timeout ]; do
        if curl -s -f http://localhost:8080/exist/apps/jinks/api/configurations > /dev/null 2>&1; then
        echo "Server is ready!"
        exit 0
        fi
        echo "Still waiting... ($elapsed seconds)"
        sleep 5
        elapsed=$((elapsed + 5))
        done
        echo "Timeout waiting for server"
        exit 1

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'

    - name: Install XST
      shell: bash
      run: npm i -g @existdb/xst

    - name: Extract ${{ inputs.app-name }} app
      working-directory: demo
      shell: bash
      run: |
        xst download "/db/apps/$INPUT_APP_NAME" . --verbose
      env:
        INPUT_APP_NAME: ${{ inputs.app-name }}

    - name: Run ${{ inputs.app-name }} tests
      shell: bash
      working-directory: demo/${{ inputs.app-name }}
      run: |
        npm install
        npx cypress run --browser firefox

    - name: Stop jinks container
      if: always()
      shell: bash
      run: docker stop jinks-server || true
