name: Run tests for demo app
description: Run Cypress tests for a demo app checked out in demo/XXX/
inputs:
  app-name:
    required: true
    description: The app name to run test for

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'

    - name: Install XST
      shell: bash
      run: npm i -g @existdb/xst

    - name: Extract ${{ inputs.app-name }} app
      working-directory: demo
      shell: bash
      run: |
        xst download "/db/apps/$INPUT_APP_NAME" . --verbose
      env:
        INPUT_APP_NAME: ${{ inputs.app-name }}

    - name: Run ${{ inputs.app-name }} tests
      shell: bash
      working-directory: demo/${{ inputs.app-name }}
      run: |
        npm install
        npm run test
