// StandardJS, should-style assertions
// GUI tests for Jinntap UI functionality
// Generated by jinks - DO NOT EDIT manually

describe("Jinntap profile", () => {
  before(() => {
    cy.login();
    cy.fixture("jinntap-document.xml", "utf8").then((docXml) => {
      cy.api({
        method: "PUT",
        url: `/api/document/${encodeURIComponent("demo/jinntap-document.xml")}`,
        body: docXml,
        failOnStatusCode: true,
        headers: {
          "content-type": "application/xml",
        },
      });
    });
  });

  beforeEach(() => {
    // Wait for page to stabilise
    cy.get("body").should("be.visible");
    cy.visit("/demo/jinntap-document.xml?template=editor.html");
  });

  it("opens an editor and can make an edit that is saved", () => {
    cy.get("jinn-tap").should("exist");
    cy.get("jinn-tap").should(
      "contain",
      "This is a text document that will receive edits.",
    );

    cy.get("jinn-tap [contenteditable]").type("Here is an edit!");

    cy.get(".saveBtn").click();

    cy.get("jinn-toast").contains("File saved as demo/jinntap-document");

    cy.reload();

    cy.get("jinn-tap").should(
      "contain",
      "This is a text document that will receive edits.",
    );
  });
});
