/**
 * StandardJS, should-style assertions
 * GUI tests for Jinntap UI functionality
 * Generated by jinks - DO NOT EDIT manually
 */

describe("Jinntap profile", () => {
  before(() => {
    cy.login();
    cy.fixture("jinntap-document.xml", "utf8").then((docXml) => {
      // encode the slash in `demo/jinntap-document` to place the document in the demo collection
      cy.api({
        method: "PUT",
        url: `/api/document/demo%2Fjinntap-document.xml`,
        body: docXml,
        failOnStatusCode: true,
        headers: {
          "content-type": "application/xml",
        },
      });
    });
  });

  beforeEach(() => {
    cy.login();
    // Wait for page to stabilise
    cy.get("body").should("be.visible");
    cy.visit("/demo/jinntap-document.xml?template=editor.html");
  });

  it("opens an editor and can make an edit that is saved", () => {
    cy.get("jinn-tap").should("exist");
    cy.get("jinn-tap").should(
      "contain",
      "This is a text document that will receive edits.",
    );

    cy.get("jinn-tap [contenteditable]").type("Here is an edit!");

    cy.get(".saveBtn").click();

    cy.get("jinn-toast").contains("File saved as demo/jinntap-document");

    cy.reload();

    cy.get("jinn-tap").should(
      "contain",
      "This is a text document that will receive edits.",
    );
  });

  // The metadata editing feature is only available when the metadata profile is installed as well.
  const isMetadataAvailable =
    '[[ $context?extends?*[.="metadata"] ]]' === "metadata";
  if (isMetadataAvailable) {
    it("can edit metadata", () => {
      cy.get("#metadataPanelBtn").click();

      cy.get('fx-control[ref="title"] input').type(" Edits are here!");
      cy.get('fx-trigger:has(fx-insert[ref="author"])').click();
      cy.get('fx-repeat[ref="author"] input').last().type("Pietje Bell");
      cy.get(".saveBtn").click();
      cy.get("jinn-toast").contains("File saved as demo/jinntap-document");
      cy.get("#metadataPanelBtn").click();

      cy.get('fx-control[ref="title"] input').should(
        "have.value",
        "Test Document for Jinntap Edits are here!",
      );
      cy.get('fx-repeat[ref="author"] input')
        .last()
        .should("have.value", "Pietje Bell");
    });
  }
});
